- platform: wunderground
  api_key: !secret wunderground_apikey
  pws_id: !secret wunderground_pws
  monitored_conditions:
      - temp_high_record_c
      - temp_high_1d_c
      - temp_c
      - temp_low_1d_c
      - temp_low_record_c
      - precip_1d
      - precip_1d_mm
      - wind_kph
      - wind_1d_kph
      - alerts
- platform: plex
